### ISSUE TITLE
Breadcrumb style changes

### ISSUE THREAD

**Issue by drklee3** [drklee3/picatch#60]
## To-Do

- [ ] Handle line breaks on mobile
- [ ] Reposition to below site title

## TBD
- [ ] Current album name goes elsewhere
